CREATE TABLE sw_sha_players
(
Id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Name VARCHAR(12) NOT NULL,
Password VARCHAR(12) NOT NULL,
Email VARCHAR(50) NOT NULL,
Rating SMALLINT UNSIGNED,
Total MEDIUMINT UNSIGNED,
Place1 SMALLINT UNSIGNED,
Place2 SMALLINT UNSIGNED,
Place3 SMALLINT UNSIGNED,
Place4 SMALLINT UNSIGNED,
PRIMARY KEY (Id),
CONSTRAINT uc_Player UNIQUE (Name,Email)
);
CREATE TABLE sw_sha_game
(
Id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
Started TIMESTAMP,
Player1 SMALLINT UNSIGNED,
Player2 SMALLINT UNSIGNED,
Player3 SMALLINT UNSIGNED,
Player4 SMALLINT UNSIGNED,
Round33 MEDIUMINT UNSIGNED,
Round34 MEDIUMINT UNSIGNED,
Round44 MEDIUMINT UNSIGNED,
Round333 MEDIUMINT UNSIGNED,
Round334 MEDIUMINT UNSIGNED,
Round344 MEDIUMINT UNSIGNED,
Round444 MEDIUMINT UNSIGNED,
PRIMARY KEY (Id),
FOREIGN KEY (Player1) REFERENCES sw_sha_players(Id),
FOREIGN KEY (Player2) REFERENCES sw_sha_players(Id),
FOREIGN KEY (Player3) REFERENCES sw_sha_players(Id),
FOREIGN KEY (Player4) REFERENCES sw_sha_players(Id)
);
CREATE TABLE sw_sha_round
(
Id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
Game SMALLINT UNSIGNED,
Score1 SMALLINT UNSIGNED,
Score2 SMALLINT UNSIGNED,
Score3 SMALLINT UNSIGNED,
Score4 SMALLINT UNSIGNED,
PRIMARY KEY (Id),
FOREIGN KEY (Game) REFERENCES sw_sha_game(Id)
);
